AWSTemplateFormatVersion: "2010-09-09"
Description: "Sherman Digital Budget"

Parameters:
  EstimatedChargesThresholdUsd:
    Description: Amount at which to trigger the alert
    Type: Number

  EmailAddress:
    Description: Email address for billing alerts
    Type: String
    AllowedPattern: ^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$

Resources:
  OrganizationBudget:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetName: "Sherman Digital Budget"
        BudgetLimit:
          Amount: !Ref EstimatedChargesThresholdUsd
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref EmailAddress
      ResourceTags:
        - Key: organization
          Value: sherman-digital

Outputs:
  BudgetId:
    Value: !Ref OrganizationBudget