AWSTemplateFormatVersion: "2010-09-09"
Description: Estimated charges alert

Parameters:
  EstimatedChargesThreshold:
    Description: Amount at which to trigger the alert
    Type: Number

  EmailAddress:
    Description: Email address for billing alerts
    Type: String
    AllowedPattern: ^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$

Resources:
  TopicEstimatedChargesAlert:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: EstimatedChargesAlert
      DisplayName: "Estimated charges exceed threshold"
      Subscription:
      - Endpoint: !Ref EmailAddress
        Protocol: email

  AlarmEstimatedCharges:
    Type: AWS::CloudWatch::Alarm
    DependsOn: TopicEstimatedChargesAlert
    Properties:
      AlarmActions:
        - !Ref TopicEstimatedChargesAlert
      AlarmDescription: "Estimated charges exceed threshold"
      AlarmName: "Estimated charges alarm"
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      EvaluationPeriods: 1
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Period: 21600 # 6 hours
      Statistic: Maximum
      Threshold: !Ref EstimatedChargesThreshold